version: "3.8"

services:
  db:
    container_name: mysql-db
    image: mysql:8.0.33
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_bootcamp
    ports:
      - "3366:3306"

  springboot-app:
    container_name: springboot-container
    image: springbootmysql
    restart: on-failure
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - db